language: haskell

ghc:
  - 7.8
  - 7.6
  - 7.4

install:
  # Testes require htpasswd utility to be installed on the system.
  - apt-get install apache2-utils
  - cabal install --only-dependencies --enable-tests --enable-benchmarks

script:
  # Option -fpedantic turns on additional wornings in addition to -Wall.
  - cabal configure --enable-tests --enable-benchmarks -fpedantic
    && cabal build
    && cabal test
    && cabal bench

  # Following line tests if sdist package is created correctly.
  - cabal sdist && cabal install dist/apache-md5-*.tar.gz
